services:
  database:
    image: postgres:latest
    container_name: inventory_database
    ports:
      - 5432:5432
    volumes:
      - ./POSTGRES_DB:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_NAME}
    networks:
     - network

  inventory-service:
    build:
      context: ./inventory_service
    container_name: inventory_service
    volumes:
      - ./inventory_backend/src:/app/src
    ports:
      - 8080:8080
    depends_on: 
      - database
    env_file:
      - .env
    networks:
     - network


volumes:
  node_modules:

networks:
  network: