spring:
    application:
        name: backend
    datasource:
        url: jdbc:postgresql://postgresdb:5432/inventory
        #url: jdbc:postgresql://localhost:5432/inventory
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
            database: postgresql
            database-plataform: org.hibernate.dialect.PostgreSQLDialect

